# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
module load cuda/11.5.2
module load python/anaconda3
module load singularity/3.9.5

export MODULEPATH="$MODULEPATH:$HOME/apps/modulefiles"
module load emacs/
module load tmux/

tmux source-file ~/.tmux.config
